name: Authentication for Dev

defaults:
  http:
    url: "{{ vars.url }}"
    headers:
      content-type: application/json

steps:
- name: Get ID
  id: get_id
  uses: shell
  with:
    cmd: echo "foobar"
  outputs:
    myid: replace(res.stdout, '\n', '')
  echo: |
    STDOUT: {{res.stdout}}

- name: Get token
  id: get_token
  uses: shell
  with:
    cmd: echo "0123456789"
  outputs:
    mytoken: replace(res.stdout, '\n', '')
  echo: |
    STDOUT: {{res.stdout}}

- name: Hello
  uses: shell
  with:
    cmd: echo "Hello, {{ vars.id }} ({{ vars.testenv }})"
  echo: |
    STDOUT: {{res.stdout}}

- name: POST
  uses: http
  with:
    post: /post
    body:
  test: res.code == 200
  echo: |
    Response Body: {{res.body}}
