name: gRPC Contract Failure
vars:
  addr: "{{GRPC_ADDR ?? 'localhost:50051'}}"

jobs:
- name: A response that breaks its .proto files
  steps:
  - name: Get a user
    uses: grpc
    with:
      addr: "{{vars.addr}}"
      service: UserService
      method: GetUser
      body:
        user_id: "123"
      proto:
        files: [./e2e/proto/users.proto]
        import_paths: [./e2e/proto]
    test: res.status_code == "OK"
