// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testdata/performance/performance_test.proto

package performance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message using map<string, string> (current approach)
type FlatDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatDataRequest) Reset() {
	*x = FlatDataRequest{}
	mi := &file_testdata_performance_performance_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatDataRequest) ProtoMessage() {}

func (x *FlatDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_performance_performance_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatDataRequest.ProtoReflect.Descriptor instead.
func (*FlatDataRequest) Descriptor() ([]byte, []int) {
	return file_testdata_performance_performance_test_proto_rawDescGZIP(), []int{0}
}

func (x *FlatDataRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type FlatDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        map[string]string      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatDataResponse) Reset() {
	*x = FlatDataResponse{}
	mi := &file_testdata_performance_performance_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatDataResponse) ProtoMessage() {}

func (x *FlatDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_performance_performance_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatDataResponse.ProtoReflect.Descriptor instead.
func (*FlatDataResponse) Descriptor() ([]byte, []int) {
	return file_testdata_performance_performance_test_proto_rawDescGZIP(), []int{1}
}

func (x *FlatDataResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

// Message using google.protobuf.Struct (alternative approach)
type StructDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructDataRequest) Reset() {
	*x = StructDataRequest{}
	mi := &file_testdata_performance_performance_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructDataRequest) ProtoMessage() {}

func (x *StructDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_performance_performance_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructDataRequest.ProtoReflect.Descriptor instead.
func (*StructDataRequest) Descriptor() ([]byte, []int) {
	return file_testdata_performance_performance_test_proto_rawDescGZIP(), []int{2}
}

func (x *StructDataRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type StructDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructDataResponse) Reset() {
	*x = StructDataResponse{}
	mi := &file_testdata_performance_performance_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructDataResponse) ProtoMessage() {}

func (x *StructDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_performance_performance_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructDataResponse.ProtoReflect.Descriptor instead.
func (*StructDataResponse) Descriptor() ([]byte, []int) {
	return file_testdata_performance_performance_test_proto_rawDescGZIP(), []int{3}
}

func (x *StructDataResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_testdata_performance_performance_test_proto protoreflect.FileDescriptor

const file_testdata_performance_performance_test_proto_rawDesc = "" +
	"\n" +
	"+testdata/performance/performance_test.proto\x12\x10performance_test\x1a\x1cgoogle/protobuf/struct.proto\"\x8b\x01\n" +
	"\x0fFlatDataRequest\x12?\n" +
	"\x04data\x18\x01 \x03(\v2+.performance_test.FlatDataRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x10FlatDataResponse\x12F\n" +
	"\x06result\x18\x01 \x03(\v2..performance_test.FlatDataResponse.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x11StructDataRequest\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"E\n" +
	"\x12StructDataResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result2g\n" +
	"\x0fFlatDataService\x12T\n" +
	"\vProcessFlat\x12!.performance_test.FlatDataRequest\x1a\".performance_test.FlatDataResponse2o\n" +
	"\x11StructDataService\x12Z\n" +
	"\rProcessStruct\x12#.performance_test.StructDataRequest\x1a$.performance_test.StructDataResponseB\x18Z\x16./testdata/performanceb\x06proto3"

var (
	file_testdata_performance_performance_test_proto_rawDescOnce sync.Once
	file_testdata_performance_performance_test_proto_rawDescData []byte
)

func file_testdata_performance_performance_test_proto_rawDescGZIP() []byte {
	file_testdata_performance_performance_test_proto_rawDescOnce.Do(func() {
		file_testdata_performance_performance_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_performance_performance_test_proto_rawDesc), len(file_testdata_performance_performance_test_proto_rawDesc)))
	})
	return file_testdata_performance_performance_test_proto_rawDescData
}

var file_testdata_performance_performance_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_testdata_performance_performance_test_proto_goTypes = []any{
	(*FlatDataRequest)(nil),    // 0: performance_test.FlatDataRequest
	(*FlatDataResponse)(nil),   // 1: performance_test.FlatDataResponse
	(*StructDataRequest)(nil),  // 2: performance_test.StructDataRequest
	(*StructDataResponse)(nil), // 3: performance_test.StructDataResponse
	nil,                        // 4: performance_test.FlatDataRequest.DataEntry
	nil,                        // 5: performance_test.FlatDataResponse.ResultEntry
	(*structpb.Struct)(nil),    // 6: google.protobuf.Struct
}
var file_testdata_performance_performance_test_proto_depIdxs = []int32{
	4, // 0: performance_test.FlatDataRequest.data:type_name -> performance_test.FlatDataRequest.DataEntry
	5, // 1: performance_test.FlatDataResponse.result:type_name -> performance_test.FlatDataResponse.ResultEntry
	6, // 2: performance_test.StructDataRequest.data:type_name -> google.protobuf.Struct
	6, // 3: performance_test.StructDataResponse.result:type_name -> google.protobuf.Struct
	0, // 4: performance_test.FlatDataService.ProcessFlat:input_type -> performance_test.FlatDataRequest
	2, // 5: performance_test.StructDataService.ProcessStruct:input_type -> performance_test.StructDataRequest
	1, // 6: performance_test.FlatDataService.ProcessFlat:output_type -> performance_test.FlatDataResponse
	3, // 7: performance_test.StructDataService.ProcessStruct:output_type -> performance_test.StructDataResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_testdata_performance_performance_test_proto_init() }
func file_testdata_performance_performance_test_proto_init() {
	if File_testdata_performance_performance_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_performance_performance_test_proto_rawDesc), len(file_testdata_performance_performance_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_testdata_performance_performance_test_proto_goTypes,
		DependencyIndexes: file_testdata_performance_performance_test_proto_depIdxs,
		MessageInfos:      file_testdata_performance_performance_test_proto_msgTypes,
	}.Build()
	File_testdata_performance_performance_test_proto = out.File
	file_testdata_performance_performance_test_proto_goTypes = nil
	file_testdata_performance_performance_test_proto_depIdxs = nil
}
