name: Browser Examples
description: Minimal test to verify browser can start

jobs:
- name: Get element text
  steps:
  - name: Simple Navigation Test
    uses: browser
    with:
      headless: true
      timeout: 30s
      actions:
      - name: navigate
        url: https://www.google.com/
      - name: wait_visible
        selector: body
      - name: text
        id: title
        selector: "title"
    test: res.code == 0
    echo: |
      Title:
      {{res.results.title}}
      -----
    outputs:
      load_time: res.time_ms

- name: Capture screenshot
  steps:
  - name: Get google
    uses: browser
    with:
      window_w: 1280
      window_h: 800
      headless: false
      timeout: 30s
      actions:
      - name: navigate
        url: https://www.google.com/
      - name: capture_screenshot
        path: ./testdata/capture_screenshot.png
        quality: 80
    test: res.code == 0
