name: Browser Examples
description: Minimal test to verify browser can start

vars:
  ci: "{{ CI ?? '' }}"

jobs:
- name: Get element text
  steps:
  - name: Simple Navigation Test
    uses: browser
    with:
      headless: true
      timeout: 1m
      actions:
      - name: navigate
        url: https://example.com/
      - name: wait_visible
        selector: h1
      - name: text
        id: heading
        selector: "h1"
    test: res.code == 0 && res.results.heading != ""
    echo: |
      Heading: {{res.results.heading}}
      -----
    outputs:
      load_time: res.time_ms

- name: Capture screenshot
  steps:
  - name: Get google
    uses: browser
    with:
      window_w: 1280
      window_h: 800
      headless: "{{ vars.ci != '' }}"
      timeout: 1m
      actions:
      - name: navigate
        url: https://www.google.com/
      - name: capture_screenshot
        path: ./testdata/capture_screenshot.png
        quality: 80
    test: res.code == 0
