name: Embedded Job

vars:
  testenv: "{{TESTENV ?? 'dev'}}"
  url: "{{TESTURL ?? 'http://localhost:8080'}}"

jobs:
- name: First job
  defaults:
    http:
      url: "{{ vars.url }}"

  steps:
  - name: Get ID
    id: shell
    uses: shell
    with:
      cmd: whoami
    test: res.code == 0
    outputs:
      login: replace(res.stdout, '\n', '')

  - name: Authentication(Embedded Job)
    id: auth
    uses: embedded
    with:
      path: "./examples/jobs/{{vars.testenv}}.yml"
      vars:
        name: foobar
        testenv: "{{ vars.testenv }}"
        id: "{{ outputs.shell.login }}"
        url: "{{ vars.url }}"
    test: res.code == 0
    outputs:
      id: res.outputs.myid
      token: res.outputs.mytoken

  - name: POST with outputs of embedded job
    uses: http
    with:
      post: /post
      headers:
        authorization: "Bearer {{outputs.auth.token}}"
        content-type: application/json
    test: res.code == 200
    echo: "{{res.body.headers.Authorization}}"
