name: Embedded Job

vars:
  testenv: "{{TESTENV ?? 'dev'}}"

jobs:
- name: First job
  steps:
  - name: Get ID
    id: shell
    uses: shell
    with:
      cmd: whoami
    test: res.code == 0
    outputs:
      login: replace(res.stdout, '\n', '')

  - name: Authentication(Embedded Job)
    id: auth
    uses: embedded
    with:
      path: "./examples/jobs/{{vars.testenv}}.yml"
      vars:
        name: foobar
        testenv: "{{ vars.testenv }}"
        id: "{{ outputs.shell.login }}"
    test: res.code == 0
    outputs:
      id: res.outputs.myid
      token: res.outputs.mytoken

  - name: Echo with outputs of embedded job
    uses: shell
    with:
      cmd: echo "Token={{outputs.auth.token}}"
    test: res.code == 0
    echo: "Authorization: Bearer {{outputs.auth.token}}"
