name: Expr-Function Example

jobs:
- name: Run match json example
  steps:
  - name: Match Regexp
    uses: shell
    with:
      cmd: echo '{"id":12345,"name":"probe"}'
    vars:
      result:
        id: 12345
        name: probe
      expected:
        id: /^\d{5}$/
        name: /^\w+$/
    test: |
      res.code == 0 &&
      match_json(vars.result, vars.expected)
    echo: diff_json(vars.result, vars.expected)
  - name: Mismatch Regexp
    uses: shell
    with:
      cmd: echo '{"id":"ABC","name":null}'
    vars:
      result:
        id: ABC
        name: null
      expected:
        id: /^\d{5}$/
        name: /^\w+$/
    test: |
      res.code == 0
    echo: diff_json(vars.result, vars.expected)

- name: Test string functions
  steps:
  - name: hasSuffix()
    uses: shell
    with:
      cmd: echo "test.json"
    test: hasSuffix(trim(res.stdout), ".json")
    outputs:
      filename: trim(res.stdout)

  - name: hasPrefix()
    uses: shell
    with:
      cmd: echo "https://example.com"
    test: hasPrefix(trim(res.stdout), "https://")
    outputs:
      url: trim(res.stdout)

  - name: indexOf()
    uses: shell
    with:
      cmd: echo "hello world"
    test: indexOf(res.stdout, "world") >= 0
    outputs:
      text: trim(res.stdout)
      position: indexOf(trim(res.stdout), "world")

  - name: verify indexOf() position
    uses: shell
    with:
      cmd: echo "hello world"
    test: indexOf(trim(res.stdout), "world") == 6
    echo: |
      The word "world" is at position {{indexOf(trim(res.stdout), "world")}}
