name: Expr-Function Example

jobs:
- name: Run match json example
  defaults:
    http:
      url: http://localhost:8080
      headers:
        content-type: application/json
        accept: application/json
  steps:
  - name: Match Regexp
    uses: http
    with:
      post: /post
      body:
        id: 12345
        name: probe
    test: |
      res.code == 200 &&
      match_json(res.body.json, vars.expected)
    echo: diff_json(res.body.json, vars.expected)
    vars:
      expected:
        id: /^\d{5}$/
        name: /^\w+$/
  - name: Mismatch Regexp
    uses: http
    with:
      post: /post
      body:
        id: ABC
        name:
    test: |
      res.code == 200
    echo: diff_json(res.body.json, vars.expected)
    vars:
      expected:
        id: /^\d{5}$/
        name: /^\w+$/

- name: Test string functions
  steps:
  - name: hasSuffix()
    uses: shell
    with:
      cmd: echo "test.json"
    test: hasSuffix(trim(res.stdout), ".json")
    outputs:
      filename: trim(res.stdout)

  - name: hasPrefix()
    uses: shell
    with:
      cmd: echo "https://example.com"
    test: hasPrefix(trim(res.stdout), "https://")
    outputs:
      url: trim(res.stdout)

  - name: indexOf()
    uses: shell
    with:
      cmd: echo "hello world"
    test: indexOf(res.stdout, "world") >= 0
    outputs:
      text: trim(res.stdout)
      position: indexOf(trim(res.stdout), "world")

  - name: verify indexOf() position
    uses: shell
    with:
      cmd: echo "hello world"
    test: indexOf(trim(res.stdout), "world") == 6
    echo: |
      The word "world" is at position {{indexOf(trim(res.stdout), "world")}}
