name: Test Flat Outputs Access

jobs:
- name: Test Flat Access
  steps:
  - name: Step with outputs
    id: auth
    uses: shell
    with:
      cmd: echo "setting up auth"
    outputs:
      token: '"secret123"'
      user_id: '"user456"'
    echo: "{{res.stdout}}"

  - name: Test both access methods
    uses: shell
    with:
      cmd: |
        echo "Step-based access: {{outputs.auth.token}}"
        echo "Flat access: {{outputs.token}}"
        echo "User ID flat: {{outputs.user_id}}"
    echo: "{{res.stdout}}"
    outputs:
      token1: '"secret123"'
      user_id1: '"user456"'

  - name: Test conflict scenario
    id: token
    uses: shell
    with:
      cmd: echo "step with conflicting ID"
    outputs:
      value: '"different_value"'
    echo: "{{res.stdout}}"

  - name: Verify conflict handling
    uses: shell
    with:
      cmd: |
        echo "Original flat token (should work): {{outputs.token}}"
        echo "Conflicting step value (should work): {{outputs.value}}"
    echo: |
      stdout: {{res.stdout}}
      outputs: {{outputs}}
