name: Iteration Literal Example

jobs:
- name: Run iteration example
  steps:
  - name: "4 times iterations: {{vars.name}}"
    uses: shell
    with:
      cmd: echo "ID={{vars.id}} Name={{vars.name}} Role={{vars.role}}"
    test: |
      res.code == 0 &&
      indexOf(res.stdout, vars.name) >= 0
    echo: "{{vars}}"
    vars:
      id: 1234
      name: default
      role: admin
    iteration:
    - {id: 2000, name: foo, role: user}
    - {id: -3000, name: bar, role: editor}
    - {id: 0.123, name: baz, role: guest}
    - {id: "5000", name: qux, role: guest}
