name: Job Skipif Demo
description: Demonstrates job-level skipif functionality with gray colored icons

vars:
  environment: development
  skip_tests: false
  run_deployment: false

jobs:
  - id: setup
    name: Environment Setup
    steps:
      - name: Initialize environment
        uses: echo
        with:
          message: "Setting up {{ vars.environment }} environment"

  - id: test
    name: Run Tests
    needs: [setup]
    skipif: vars.skip_tests
    steps:
      - name: Execute unit tests
        uses: echo
        with:
          message: "Running unit tests in {{ vars.environment }}"
      - name: Execute integration tests
        uses: echo
        with:
          message: "Running integration tests"

  - id: build
    name: Build Application
    needs: [setup]
    steps:
      - name: Compile application
        uses: echo
        with:
          message: "Building application for {{ vars.environment }}"

  - id: deploy-staging
    name: Deploy to Staging
    needs: [build, test]
    skipif: vars.environment != "staging"
    steps:
      - name: Deploy application
        uses: echo
        with:
          message: "Deploying to staging environment"

  - id: deploy-production
    name: Deploy to Production
    needs: [build, test]
    skipif: vars.environment != "production" || !vars.run_deployment
    steps:
      - name: Deploy application
        uses: echo
        with:
          message: "Deploying to production environment"

  - id: cleanup
    name: Cleanup
    needs: [build]
    steps:
      - name: Clean temporary files
        uses: echo
        with:
          message: "Cleaning up temporary files"