name: Job Skipif Literal Test
description: Test job skipif with literal boolean

jobs:
- id: always-run
  name: Always Run Job
  steps:
  - name: Basic task
    uses: http
    with:
      url: https://httpbin.org
      get: /status

- id: should-skip
  name: Should Be Skipped
  needs: [always-run]
  skipif: true
  steps:
  - name: This should not run
    uses: http
    with:
      url: https://httpbin.org
      get: /status

- id: cleanup
  name: Final Cleanup
  needs: [always-run]
  steps:
  - name: Clean up task
    uses: http
    with:
      url: https://httpbin.org
      get: /status
