name: Needs Dependency Test
defaults: &def
  http:
    url: http://localhost:8080
    headers:
      content-type: application/json
      accept: application/json

jobs:
- name: Setup Phase
  id: setup
  defaults: *def
  steps:
  - name: Initialize data
    uses: http
    with:
      post: /post
      body:
        message: "Setup completed"
        setup_id: "{{random_int(9999)}}"
    test: res.code == 200
    echo: res.body.json.setup_id

- name: Phase A (Twice)
  id: test-a
  defaults: *def
  needs: [setup]
  repeat:
    count: 2
    interval: 3
  steps:
  - name: Run test A
    uses: http
    with:
      post: /post
      body:
        message: "Test A executed"
        depends_on: setup
    test: res.code == 200

- name: Test Phase B
  id: test-b
  needs: [setup]
  defaults: *def
  steps:
  - name: Run test B
    uses: http
    with:
      post: /post
      body:
        message: "Test B executed"
        depends_on: setup
    test: res.code == 200

- name: Test Phase C (Will Fail)
  id: test-c
  needs: [test-b]
  defaults: *def
  steps:
  - name: Failing step C
    uses: http
    with:
      post: /status/500
      body:
        message: "Test C executed"
        depends_on: test-b
    test: res.code == 200

- name: Test Phase D (Depends on C)
  id: test-d
  needs: [test-c]
  defaults: *def
  steps:
  - name: Should not run
    uses: http
    with:
      post: /post
      body:
        message: "Test D executed"
        depends_on: test-c
    test: res.code == 200

- name: Cleanup Phase
  id: cleanup
  needs: [test-a, test-b]
  defaults: *def
  steps:
  - name: Cleanup resources
    uses: http
    with:
      post: /post
      body:
        message: "Cleanup completed"
        after: ["test-a", "test-b"]
    test: res.code == 200

- name: Test Phase Z
  id: test-z
  defaults: *def
  steps:
  - name: Run standalone test Z (Independent)
    uses: http
    with:
      post: /post
      body:
        message: "Test Z executed"
    test: res.code == 200
