name: Nested YAML Alias

vars:
  test_value: "{{ TEST_VALUE ?? 'test' }}"

aliases:
  base_value: &base_value "{{ vars.test_value }}"
  default_config: &default_config
    content-type: application/json
    accept: application/json
  auth_config: &a_config
    authorization: Bearer xxxxxxxxxxxxx
  custom_config: &x_config
    x-foo: foo
  bundle_config: &b_config
    <<: [*a_config, *x_config]
    x-bar: bar
    x-baz: baz
  double_mergekey_config: &d_config
    <<: *a_config
    <<: *x_config
    x-bar: bar
    x-baz: baz

jobs:
- name: Test Job
  steps:
  - name: Test basic alias
    uses: shell
    with:
      cmd: echo "hello"
    vars:
      base: *base_value
      config: *default_config
    test: |
      res.code == 0 &&
      replace(res.stdout, '\n', '') == "hello"
    echo: |
      Base value: {{vars.base}}
    outputs:
      result: replace(res.stdout, '\n', '')

  - name: Verify mergekey list
    uses: shell
    with:
      cmd: echo "testing mergekey"
    vars:
      config: *b_config
    test: |
      res.code == 0 &&
      vars.config.authorization == "Bearer xxxxxxxxxxxxx" &&
      vars.config["x-bar"] == "bar" &&
      vars.config["x-baz"] == "baz" &&
      vars.config["x-foo"] == "foo"
    echo: |
      Config: {{vars.config}}

  - name: Verify double mergekey
    uses: shell
    with:
      cmd: echo "testing double mergekey"
    vars:
      config: *d_config
    test: |
      res.code == 0 &&
      vars.config.authorization == "Bearer xxxxxxxxxxxxx" &&
      vars.config["x-bar"] == "bar" &&
      vars.config["x-baz"] == "baz" &&
      vars.config["x-foo"] == "foo"
    echo: |
      Config: {{vars.config}}
