name: Nested YAML Alias

vars:
  api_endpoint: "{{ API_ENDPOINT ?? 'http://localhost:8080' }}"

aliases:
  endpoint: &base_url "{{ vars.api_endpoint }}"
  headers: &default_headers
    content-type: application/json
    accept: application/json
  auth_headers: &a_headers
    authorization: Bearer xxxxxxxxxxxxx
  custom_headers: &x_headers
    x-foo: foo
  bundle_headers: &b_headers
    <<: [*a_headers, *x_headers]
    x-bar: bar
    x-baz: baz

jobs:
- name: Test Job
  defaults:
    http:
      url: *base_url
      headers: *default_headers

  steps:
  - name: Post json
    uses: http
    with:
      post: /post
      body:
        message: hello
    test: |
      res.code == 200 &&
      res.body.json.message == "hello"
    echo: |
      IP: {{res.body.origin}}
    outputs:
      ip: res.body.origin

  - name: Post with auth
    uses: http
    with:
      headers: *b_headers
      post: /post
      body:
        message: hello
    test: |
      res.code == 200 &&
      hasPrefix(res.body.headers.Authorization[0], "Bearer ") &&
      res.body.headers["X-Bar"][0] == "bar" &&
      res.body.headers["X-Baz"][0] == "baz" &&
      res.body.headers["X-Foo"][0] == "foo"
    echo: |
      {{res.body.headers}}
