name: Outputs Literal Example

jobs:
- name: Test Job 1
  id: job1
  steps:
  - name: Get identifier with set to outputs
    id: step1
    uses: shell
    with:
      cmd: echo "test-identifier-12345"
    outputs:
      token: replace(res.stdout, '\n', '')

  - name: Use outputs identifier
    uses: shell
    with:
      cmd: echo "Identifier is {{outputs.step1.token}}"
    vars:
      foo:
        bar: "{{outputs.step1.token}}"
    echo: |
      Identifier from stdout: {{replace(res.stdout, '\n', '')}}
      bar from vars:{{vars.foo.bar}}

- name: Test Job 2
  needs: [job1]
  steps:
  - name: Use shared outputs over job
    uses: shell
    with:
      cmd: echo "Using identifier {{outputs.step1.token}}"
    echo: |
      Full: {{outputs.step1.token }}
      Short: {{outputs.token}}
