name: Repeat job example
jobs:
- name: Job with repeat index
  repeat:
    count: 3
    interval: 2s

  steps:
    - name: Test repeat_index in echo - {{vars.name}}
      uses: http
      with:
        url: http://localhost:8080
        headers:
          content-type: application/json
        post: /post
        body:
          name: "{{vars.name}}"
          index: "{{repeat_index}}"
      echo: |
        Current iteration: {{repeat_index}}
      wait: 500ms
      vars:
        name: repeat-{{repeat_index}}

    - name: Test repeat_index in test condition - {{vars.name}}
      uses: hello
      test: "repeat_index >= 1"
      wait: 500ms
      vars:
        name: Hello

    - name: Test repeat_index calculation - {{repeat_index}}
      uses: hello
      echo: |
        Calculated value: {{repeat_index * 10}}
      wait: 500ms
