name: REST API Example
vars:
  token: "{{TOKEN ?? 'secret'}}"
  url: "{{URL ?? 'https://httpbin.org'}}"

jobs:
- name: "Request to {{vars.url}}"
  defaults:
    http:
      url: "{{vars.url}}"
      headers:
        authorization: "Bearer {{vars.token}}"
        content-type: application/json
        accept: application/json
  steps:
  - name: Post
    id: hello
    uses: http
    with:
      post: /post
      body:
        message: hello
    test: |
      res.code == 200 &&
      res.body.json.message == "hello"
    echo: |
      IP: {{res.body.origin}}
    outputs:
      ip: res.body.origin
  - name: Get
    uses: http
    with:
      get: /get
    test: |
      res.code == 200 &&
      res.body.url == "https://httpbin.org/get"
  - name: Update
    uses: http
    with:
      put: /put
      body:
        ip: "{{outputs.hello.ip}}"
    test: |
      res.code == 200 &&
      res.body.json.ip == outputs.hello.ip
  - name: Patch
    uses: http
    with:
      patch: /patch
      body:
        message: yo
  - name: Delete
    uses: http
    with:
      delete: /delete
    test: |
      res.code == 200
