name: Test Outputs Variables

x_defaults: &defaults
  http:
    url: https://httpbin.org
    headers:
      content-type: application/json

jobs:
- name: Test Job 1
  id: job1
  defaults: *defaults
  steps:
  - name: Get my IP with set to outputs
    id: step1
    uses: http
    with:
      get: /get
    echo: "{res.body.origin}"
    outputs:
      token: res.body.origin

  - name: Post by outputs ip
    uses: http
    with:
      post: /post
      body:
        myip: "{outputs.step1.token}"
    echo: "myip: {res.body.json.myip}\nbar:{vars.foo.bar}"
    vars:
      foo:
        bar: "{outputs.step1.token}"

- name: Test Job 2
  needs: [job1]
  defaults: *defaults
  steps:
  - name: Use shared outputs over job
    uses: http
    with:
      post: /post
      body:
        myip: "{outputs.step1.token}"
    echo: "{outputs.step1.token}"
