name: Test Outputs Variables

x_defaults: &defaults
  http:
    url: http://localhost:8080
    headers:
      content-type: application/json

jobs:
- name: Test Job 1
  id: job1
  defaults: *defaults
  steps:
  - name: Get my IP with set to outputs
    id: step1
    uses: http
    with:
      get: /get
    outputs:
      token: res.body.origin

  - name: Post by outputs ip
    uses: http
    with:
      post: /post
      body:
        myip: "{{outputs.step1.token}}"
    vars:
      foo:
        bar: "{{outputs.step1.token}}"
    echo: |
      IP from res: {{res.body.json.myip}}
      bar from vars:{{vars.foo.bar}}

- name: Test Job 2
  needs: [job1]
  defaults: *defaults
  steps:
  - name: Use shared outputs over job
    uses: http
    with:
      post: /post
      body:
        myip: "{{outputs.step1.token}}"
    echo: |
      Full: {{outputs.step1.token }}
      Short: {{outputs.token}}
