name: Yaml Alias by Concating Files
description: With yaml-shared.yml

jobs:
- name: Alias headers
  defaults:
    http:
      url: http://localhost:8080
  steps:
  - name: Post
    uses: http
    with:
      post: /post
      headers:
        <<: *x_foobar_headers
      body:
        message: hello
    test: |
      res.code == 200 &&
      res.body.headers["X-Foobar"] == "bazbazbaz"
    echo: |
      Request Headers: {{res.body.headers}}
