name: Resource usage experiments
jobs:
  case1:
    steps:
      - name: Sender 1
        use: bulkmail
        with:
          addr: localhost:5871
          from: alice@msa1.local
          to: bob@mx1.local
          my-hostname: msa1-local
          subject: Experiment: Sender 1
          session: 5
          message: {{ vars.message }}
          length: 1000
      repeat:
        times: 4
        interval: 10sec
        vars:
          message: {{ math(10^(i+3)) }}
  case2:
    steps:
      - name: Sender 2
        use: bulkmail
        with:
          addr: localhost:5872
          from: carol@msa2.local
          to: bob@mx2.local
          my-hostname: msa2-local
          subject: Experiment: Sender 2
          session: 5
          message: {{ vars.message }}
          length: 1000
      repeat:
        times: 4
        interval: 10sec
        vars:
          message: {{ math(10^(i+3)) }}
  case3:
    steps:
      - name: Sender 3
        use: bulkmail
        with:
          addr: localhost:5873
          from: mallory@msa3.local
          to: bob@mx3.local
          my-hostname: msa3-local
          subject: Experiment: Sender 3
          session: 5
          message: {{ vars.message }}
          length: 1000
      repeat:
        times: 4
        interval: 10sec
        vars:
          message: {{ math(10^(i+3)) }}
