// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: pb/actions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	With  *structpb.Struct       `protobuf:"bytes,2,opt,name=with,proto3" json:"with,omitempty"`
	// The state the action left in the job before, for a stateful action.
	State *structpb.Struct `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// The step the action runs for.
	Step *Step `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	// What the run allows the action to do, which the action keeps to.
	Guard *Guard `protobuf:"bytes,5,opt,name=guard,proto3" json:"guard,omitempty"`
	// The names the workflow gives its external actions, each with the action
	// it stands for, for an action that runs steps of its own.
	Actions       map[string]string `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_pb_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_pb_actions_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetWith() *structpb.Struct {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *RunRequest) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RunRequest) GetStep() *Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *RunRequest) GetGuard() *Guard {
	if x != nil {
		return x.Guard
	}
	return nil
}

func (x *RunRequest) GetActions() map[string]string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// Guard is what the run allows actions to do, set by whoever runs probe
// rather than by the workflow. An action that keeps to it refuses what it
// does not allow; an empty guard allows everything.
type Guard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether only what reads is allowed, and nothing that writes.
	ReadOnly bool `protobuf:"varint,1,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// The hosts actions may connect to, such as api.example.com,
	// localhost:8080 or *.internal; empty for any.
	AllowHosts []string `protobuf:"bytes,2,rep,name=allow_hosts,json=allowHosts,proto3" json:"allow_hosts,omitempty"`
	// The actions run under the guard although they do not keep to it.
	AllowActions []string `protobuf:"bytes,3,rep,name=allow_actions,json=allowActions,proto3" json:"allow_actions,omitempty"`
	// The kinds of guard each action keeps to itself, such as read-only and
	// allow-host, keyed by the action as a step's uses names it.
	Keeps         map[string]*GuardKinds `protobuf:"bytes,5,rep,name=keeps,proto3" json:"keeps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guard) Reset() {
	*x = Guard{}
	mi := &file_pb_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guard) ProtoMessage() {}

func (x *Guard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guard.ProtoReflect.Descriptor instead.
func (*Guard) Descriptor() ([]byte, []int) {
	return file_pb_actions_proto_rawDescGZIP(), []int{1}
}

func (x *Guard) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Guard) GetAllowHosts() []string {
	if x != nil {
		return x.AllowHosts
	}
	return nil
}

func (x *Guard) GetAllowActions() []string {
	if x != nil {
		return x.AllowActions
	}
	return nil
}

func (x *Guard) GetKeeps() map[string]*GuardKinds {
	if x != nil {
		return x.Keeps
	}
	return nil
}

// GuardKinds are the kinds of guard an action keeps to.
type GuardKinds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []string               `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardKinds) Reset() {
	*x = GuardKinds{}
	mi := &file_pb_actions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardKinds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardKinds) ProtoMessage() {}

func (x *GuardKinds) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardKinds.ProtoReflect.Descriptor instead.
func (*GuardKinds) Descriptor() ([]byte, []int) {
	return file_pb_actions_proto_rawDescGZIP(), []int{2}
}

func (x *GuardKinds) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// Step tells an action about the step it runs for, for it to use as it sees
// fit, such as to say where a request comes from.
type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The run of probe, the same for every step of every job in it.
	RunId   string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobId   string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName string `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	// The position of the step in the job, from 0.
	Index int64 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	// The id the step is given, or empty.
	Id   string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Which run of a repeated job, from 0.
	Repeat int64 `protobuf:"varint,7,opt,name=repeat,proto3" json:"repeat,omitempty"`
	// Which attempt of a retried step, from 1.
	Attempt       int64 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_pb_actions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_pb_actions_proto_rawDescGZIP(), []int{3}
}

func (x *Step) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Step) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Step) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Step) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetRepeat() int64 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

func (x *Step) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type RunResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// The state the action leaves in the job, or none to keep it as it was.
	State         *structpb.Struct `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_pb_actions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_actions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_pb_actions_proto_rawDescGZIP(), []int{4}
}

func (x *RunResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunResponse) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

var File_pb_actions_proto protoreflect.FileDescriptor

const file_pb_actions_proto_rawDesc = "" +
	"\n" +
	"\x10pb/actions.proto\x12\x02pb\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x02\n" +
	"\n" +
	"RunRequest\x12+\n" +
	"\x04with\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04with\x12-\n" +
	"\x05state\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05state\x12\x1c\n" +
	"\x04step\x18\x04 \x01(\v2\b.pb.StepR\x04step\x12\x1f\n" +
	"\x05guard\x18\x05 \x01(\v2\t.pb.GuardR\x05guard\x125\n" +
	"\aactions\x18\x06 \x03(\v2\x1b.pb.RunRequest.ActionsEntryR\aactions\x1a:\n" +
	"\fActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02R\x04args\"\xef\x01\n" +
	"\x05Guard\x12\x1b\n" +
	"\tread_only\x18\x01 \x01(\bR\breadOnly\x12\x1f\n" +
	"\vallow_hosts\x18\x02 \x03(\tR\n" +
	"allowHosts\x12#\n" +
	"\rallow_actions\x18\x03 \x03(\tR\fallowActions\x12*\n" +
	"\x05keeps\x18\x05 \x03(\v2\x14.pb.Guard.KeepsEntryR\x05keeps\x1aH\n" +
	"\n" +
	"KeepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.pb.GuardKindsR\x05value:\x028\x01J\x04\b\x04\x10\x05R\akeeping\"\"\n" +
	"\n" +
	"GuardKinds\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\"\xbb\x01\n" +
	"\x04Step\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x03R\x05index\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x16\n" +
	"\x06repeat\x18\a \x01(\x03R\x06repeat\x12\x18\n" +
	"\aattempt\x18\b \x01(\x03R\aattempt\"z\n" +
	"\vRunResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result\x12-\n" +
	"\x05state\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05stateJ\x04\b\x02\x10\x03R\x05error21\n" +
	"\aActions\x12&\n" +
	"\x03Run\x12\x0e.pb.RunRequest\x1a\x0f.pb.RunResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_actions_proto_rawDescOnce sync.Once
	file_pb_actions_proto_rawDescData []byte
)

func file_pb_actions_proto_rawDescGZIP() []byte {
	file_pb_actions_proto_rawDescOnce.Do(func() {
		file_pb_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_actions_proto_rawDesc), len(file_pb_actions_proto_rawDesc)))
	})
	return file_pb_actions_proto_rawDescData
}

var file_pb_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_actions_proto_goTypes = []any{
	(*RunRequest)(nil),      // 0: pb.RunRequest
	(*Guard)(nil),           // 1: pb.Guard
	(*GuardKinds)(nil),      // 2: pb.GuardKinds
	(*Step)(nil),            // 3: pb.Step
	(*RunResponse)(nil),     // 4: pb.RunResponse
	nil,                     // 5: pb.RunRequest.ActionsEntry
	nil,                     // 6: pb.Guard.KeepsEntry
	(*structpb.Struct)(nil), // 7: google.protobuf.Struct
}
var file_pb_actions_proto_depIdxs = []int32{
	7,  // 0: pb.RunRequest.with:type_name -> google.protobuf.Struct
	7,  // 1: pb.RunRequest.state:type_name -> google.protobuf.Struct
	3,  // 2: pb.RunRequest.step:type_name -> pb.Step
	1,  // 3: pb.RunRequest.guard:type_name -> pb.Guard
	5,  // 4: pb.RunRequest.actions:type_name -> pb.RunRequest.ActionsEntry
	6,  // 5: pb.Guard.keeps:type_name -> pb.Guard.KeepsEntry
	7,  // 6: pb.RunResponse.result:type_name -> google.protobuf.Struct
	7,  // 7: pb.RunResponse.state:type_name -> google.protobuf.Struct
	2,  // 8: pb.Guard.KeepsEntry.value:type_name -> pb.GuardKinds
	0,  // 9: pb.Actions.Run:input_type -> pb.RunRequest
	4,  // 10: pb.Actions.Run:output_type -> pb.RunResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pb_actions_proto_init() }
func file_pb_actions_proto_init() {
	if File_pb_actions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_actions_proto_rawDesc), len(file_pb_actions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_actions_proto_goTypes,
		DependencyIndexes: file_pb_actions_proto_depIdxs,
		MessageInfos:      file_pb_actions_proto_msgTypes,
	}.Build()
	File_pb_actions_proto = out.File
	file_pb_actions_proto_goTypes = nil
	file_pb_actions_proto_depIdxs = nil
}
